-- 코드를 작성해주세요
WITH MAX_FISH AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO FI
    GROUP BY FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO FI
LEFT JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE (FI.FISH_TYPE, LENGTH) IN (SELECT * FROM MAX_FISH)